package frames;

import GProyectos.GestProyecto;
import gestor.controlador.Proyecto;
import gestor.controlador.Usuario;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmGestProyecto extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form frmGestiones
     */
    public frmGestProyecto(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        cargarListaUsuarios();
        cargarDatos();
        this.setLocationRelativeTo(null);
    }

    //metodo para cargar la lista de usuarios en el cmb de persona reponsable
    public void cargarListaUsuarios() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) cmbResponsable.getModel();
        modelo.addElement("Seleccione un responsable:");
        Usuario listusuarios = new Usuario();
        for (String x : listusuarios.todosUsuario()) {
            modelo.addElement(x);
        }
        cmbResponsable.setModel(modelo);
    }

    public void cargarDatos() {
        DefaultTableModel model = (DefaultTableModel) jtProyecto.getModel();
        model.setNumRows(0);

        GestProyecto dProyecto = new GestProyecto();
        String nombre = this.usuario.getNombre() + " ("
                + this.usuario.getEmail() + ")";
        ArrayList<Proyecto> miListaProyecto = dProyecto.buscarProyectoResponsable(nombre);

        if (!miListaProyecto.isEmpty()) {
            String datos[] = new String[6];
            for (Proyecto proyecto : miListaProyecto) {
                datos[0] = String.valueOf(proyecto.getIdProyecto());
                datos[1] = proyecto.getNombreProyecto();
                datos[2] = proyecto.getPersonaResp();
                datos[3] = String.valueOf(proyecto.getFechaInicio());
                datos[4] = String.valueOf(proyecto.getFechaFinal());
                datos[5] = proyecto.isFinalizada() ? "Sí" : "No";
                model.addRow(datos);
            }
        }
        jtProyecto.setModel(model);
    }

    public void limpiar() {
        txtIdProyecto.setText("");
        txtNombre.setText("");
        cmbResponsable.setSelectedIndex(0);
        ftxtFechaInicio.setText("");
        ftxtFechaFinal.setText("");
        cmbFinalizado.setSelectedIndex(-1);
        txtIdProyecto.requestFocus();
    }

    public boolean finalizado() {
        if (cmbFinalizado.getSelectedIndex() == 1) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdProyecto = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmbResponsable = new javax.swing.JComboBox<>();
        ftxtFechaInicio = new javax.swing.JFormattedTextField();
        ftxtFechaFinal = new javax.swing.JFormattedTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cmbFinalizado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProyecto = new javax.swing.JTable();
        btnListaProyectos = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnMisProyectos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Proyectos");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Proyecto"));

        jLabel5.setText("Id Proyecto");

        jLabel1.setText("Nombre");

        jLabel2.setText("Persona Responsable");

        jLabel3.setText("Fecha de Inicio");

        jLabel4.setText("Fecha de Finalización");

        ftxtFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        ftxtFechaInicio.setToolTipText("Formato: yyyy-mm-dd");

        ftxtFechaFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        ftxtFechaFinal.setToolTipText("Formato: yyyy-mm-dd");

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/agregar-archivo.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Formato de fechas: yyyy-mm-dd");

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel7.setText("¿Proyecto Finalizado?");

        btnBuscar.setText("<html>Búsqueda<br>Avanzada</html>");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cmbFinalizado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Sí" }));
        cmbFinalizado.setSelectedIndex(-1);
        cmbFinalizado.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(74, 74, 74))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(83, 83, 83)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdProyecto)
                            .addComponent(txtNombre)
                            .addComponent(cmbResponsable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftxtFechaInicio)
                            .addComponent(ftxtFechaFinal)
                            .addComponent(cmbFinalizado, 0, 380, Short.MAX_VALUE)))
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ftxtFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(cmbFinalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jtProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Proyecto", "Nombre Proyecto", "Responsable", "Inicio", "Fin", "¿Finalizado?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProyectoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtProyecto);

        btnListaProyectos.setText("Ver todos los proyectos");
        btnListaProyectos.setToolTipText("Muestra la lista de todos los proyectos en la base de datos.");
        btnListaProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaProyectosActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnMisProyectos.setText("Ver solo mis proyectos");
        btnMisProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisProyectosActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListaProyectos)
                        .addGap(48, 48, 48)
                        .addComponent(btnMisProyectos)
                        .addGap(46, 46, 46)
                        .addComponent(btnVolver)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListaProyectos)
                    .addComponent(btnVolver)
                    .addComponent(btnMisProyectos)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        frmMenuPrincipal menuPrincipal = new frmMenuPrincipal(this.usuario);
        this.dispose();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        //Valida si todos los espacios estan completos, si no, envia mensaje de error
        if (txtIdProyecto.getText().isEmpty()
                || txtNombre.getText().isEmpty()
                || cmbResponsable.getSelectedIndex() == 0
                || ftxtFechaInicio.getText().isEmpty()
                || ftxtFechaFinal.getText().isEmpty()
                || cmbFinalizado.getSelectedIndex() == -1) { // Verifica que se haya seleccionado una opción

            JOptionPane.showMessageDialog(this, "Rellene todos los espacios para agregar el proyecto",
                    "Espacios vacíos", JOptionPane.WARNING_MESSAGE);
            return;

        } else {
            GestProyecto gestProyecto = new GestProyecto();
            Proyecto p = new Proyecto(Integer.parseInt(txtIdProyecto.getText()),
                    txtNombre.getText(),
                    cmbResponsable.getSelectedItem().toString(),
                    LocalDate.parse(ftxtFechaInicio.getText()),
                    LocalDate.parse(ftxtFechaFinal.getText()),
                    finalizado());
            gestProyecto.insertarProyecto(p);

            cargarDatos();
            limpiar();
        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtProyecto.getModel();
        model.setNumRows(0);

        GestProyecto dProyecto = new GestProyecto();
        ArrayList<Proyecto> miListaProyecto = new ArrayList<>();

        //Creo un OptionDialog para que el usuario seleccione el tipo de búsqueda
        String[] opciones = {"Id", "Nombre", "Persona Responsable", "Fecha de Inicio",
            "Fecha de Finalización", "Estado de Finalización"};
        this.toBack();
        int x = JOptionPane.showOptionDialog(null, "Seleccione el filtro de búsqueda que desear realizar:",
                "Búsqueda Avanzada",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);

        //Hago un switch para darle el valor a la lista dependiendo del tipo de búsqueda seleccionado
        //así le doy el valor correcto dependiendo del método asignado
        switch (x) {
            case 0:
                miListaProyecto = dProyecto.buscarProyectoId(Integer.parseInt(txtIdProyecto.getText()));
                break;
            case 1:
                miListaProyecto = dProyecto.buscarProyectoNombre(txtNombre.getText());
                break;
            case 2:
                miListaProyecto = dProyecto.buscarProyectoResponsable(cmbResponsable.getSelectedItem().toString());
                break;
            case 3:
                miListaProyecto = dProyecto.buscarProyectoFechaInicio(LocalDate.parse(ftxtFechaInicio.getText()));
                break;
            case 4:
                miListaProyecto = dProyecto.buscarProyectoFechaFinal(LocalDate.parse(ftxtFechaFinal.getText()));
                break;
            case 5:
                miListaProyecto = dProyecto.buscarProyectoFinalizada(finalizado());
                break;
            default:
                miListaProyecto = new ArrayList<>();
                break;
        }

        if (miListaProyecto != null && !miListaProyecto.isEmpty()) {
            String datos[] = new String[6];
            for (Proyecto proyecto : miListaProyecto) {
                datos[0] = String.valueOf(proyecto.getIdProyecto());
                datos[1] = proyecto.getNombreProyecto();
                datos[2] = proyecto.getPersonaResp();
                datos[3] = String.valueOf(proyecto.getFechaInicio());
                datos[4] = String.valueOf(proyecto.getFechaFinal());
                datos[5] = proyecto.isFinalizada() ? "Sí" : "No";
                model.addRow(datos);
            }
        } else {
            this.toBack();
            JOptionPane.showMessageDialog(null, "No se encontraron resultados.", "Búsqueda Avanzada", JOptionPane.INFORMATION_MESSAGE);
        }
        jtProyecto.setModel(model);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListaProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaProyectosActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtProyecto.getModel();
        model.setNumRows(0);

        GestProyecto dProyecto = new GestProyecto();
        ArrayList<Proyecto> miListaProyecto = dProyecto.todosProyecto();

        if (!miListaProyecto.isEmpty()) {
            String datos[] = new String[6];
            for (Proyecto proyecto : miListaProyecto) {
                datos[0] = String.valueOf(proyecto.getIdProyecto());
                datos[1] = proyecto.getNombreProyecto();
                datos[2] = proyecto.getPersonaResp();
                datos[3] = String.valueOf(proyecto.getFechaInicio());
                datos[4] = String.valueOf(proyecto.getFechaFinal());
                datos[5] = proyecto.isFinalizada() ? "Sí" : "No";
                model.addRow(datos);
            }
        }
        jtProyecto.setModel(model);
    }//GEN-LAST:event_btnListaProyectosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnMisProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisProyectosActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnMisProyectosActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        GestProyecto dProyecto = new GestProyecto();
        Proyecto proyecto = new Proyecto(Integer.parseInt(txtIdProyecto.getText()),
                txtNombre.getText(),
                cmbResponsable.getSelectedItem().toString(),
                LocalDate.parse(ftxtFechaInicio.getText()),
                LocalDate.parse(ftxtFechaFinal.getText()),
                finalizado());
        dProyecto.modificarProyecto(proyecto);

        cargarDatos();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jtProyectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProyectoMouseClicked
        int filaseleccionada;
        try {
            filaseleccionada = jtProyecto.getSelectedRow();
            if (filaseleccionada == -1) {
                this.toBack();
                JOptionPane.showMessageDialog(null, "No se encuentra ninguna fila seleciconada",
                        "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String id = (String) jtProyecto.getValueAt(filaseleccionada, 0);
                String nombre = (String) jtProyecto.getValueAt(filaseleccionada, 1);
                String respon = (String) jtProyecto.getValueAt(filaseleccionada, 2);
                String fechaIn = (String) jtProyecto.getValueAt(filaseleccionada, 3);
                String fechaFin = (String) jtProyecto.getValueAt(filaseleccionada, 4);
                String fin = (String) jtProyecto.getValueAt(filaseleccionada, 5);
                //Se llenan los campos con la fila seleccionada
                txtIdProyecto.setText(id);
                txtNombre.setText(nombre);
                cmbResponsable.setSelectedItem(respon);
                ftxtFechaInicio.setText(fechaIn);
                ftxtFechaFinal.setText(fechaFin);
                cmbFinalizado.setSelectedItem(fin);
            }
        } catch (Exception e) {
            this.toBack();
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtProyectoMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        GestProyecto dProyecto = new GestProyecto();
        Proyecto proyecto = new Proyecto(Integer.parseInt(txtIdProyecto.getText()),
                txtNombre.getText(),
                cmbResponsable.getSelectedItem().toString(),
                LocalDate.parse(ftxtFechaInicio.getText()),
                LocalDate.parse(ftxtFechaFinal.getText()),
                finalizado());
        dProyecto.eliminarProyecto(proyecto);

        cargarDatos();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGestProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGestProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGestProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGestProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmGestProyecto(this.usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListaProyectos;
    private javax.swing.JButton btnMisProyectos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbFinalizado;
    private javax.swing.JComboBox<String> cmbResponsable;
    private javax.swing.JFormattedTextField ftxtFechaFinal;
    private javax.swing.JFormattedTextField ftxtFechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtProyecto;
    private javax.swing.JTextField txtIdProyecto;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
