package frames;

import GProyectos.GestNotificacion;
import GProyectos.GestProyecto;
import GProyectos.GestTarea;
import gestor.controlador.Notificacion;
import gestor.controlador.Proyecto;
import gestor.controlador.Tarea;
import gestor.controlador.Usuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class frmMenuPrincipal extends javax.swing.JFrame {

    private Usuario usuario;

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        this.setLocationRelativeTo(null);
        cargarDatos();
        jLabelNombre.setText("¡Bienvenidx " + this.usuario.getNombre() + "!");
        iniciarNotificaciones();
    }

    public void cargarDatos() {
        DefaultTableModel model = (DefaultTableModel) jtProyecto.getModel();
        model.setNumRows(0);

        GestProyecto dProyecto = new GestProyecto();
        String nombre = this.usuario.getNombre() + " ("
                + this.usuario.getEmail() + ")";
        ArrayList<Proyecto> miListaProyecto = dProyecto.buscarProyectoResponsable(nombre);

        if (!miListaProyecto.isEmpty()) {
            String datos[] = new String[6];
            for (Proyecto proyecto : miListaProyecto) {
                datos[0] = String.valueOf(proyecto.getIdProyecto());
                datos[1] = proyecto.getNombreProyecto();
                datos[2] = proyecto.getPersonaResp();
                datos[3] = String.valueOf(proyecto.getFechaInicio());
                datos[4] = String.valueOf(proyecto.getFechaFinal());
                datos[5] = proyecto.isFinalizada() ? "Sí" : "No";
                model.addRow(datos);
            }
        }
        jtProyecto.setModel(model);

        DefaultTableModel model2 = (DefaultTableModel) jtTarea.getModel();
        model2.setNumRows(0);

        GestTarea dTarea = new GestTarea();
        ArrayList<Tarea> miListaTarea = dTarea.buscarTareaResponsable(nombre);

        if (!miListaTarea.isEmpty()) {
            String datos2[] = new String[8];
            for (Tarea tarea : miListaTarea) {
                datos2[0] = tarea.getIdTarea();
                datos2[1] = tarea.getNombreProyecto();
                datos2[2] = tarea.getNombreTarea();
                datos2[3] = tarea.getResponsableTarea();
                datos2[4] = String.valueOf(tarea.getFechaDeVencimiento());
                datos2[5] = tarea.getPrioridad();
                datos2[6] = tarea.getFinalizadaTarea() ? "Sí" : "No";
                datos2[7] = tarea.getComentario();
                model2.addRow(datos2);
            }
        }
        jtTarea.setModel(model2);
    }
    
    private void iniciarNotificaciones() {
        GestNotificacion gestNotificacion = new GestNotificacion();
        GestTarea gestTarea = new GestTarea();
        
        Notificacion preferenciaNotificacion = gestNotificacion.buscarPreferenciaPorUsuario(usuario.getNombre() + " (" + usuario.getEmail() + ")");

        if (preferenciaNotificacion != null && !preferenciaNotificacion.isDetener()) {
            ArrayList<Tarea> tareasDelUsuario = gestTarea.buscarTareaResponsable(usuario.getNombre() + " (" + usuario.getEmail() + ")");
            
            //Crea y ejecuta un hilo de notificación para cada tarea
            for (Tarea tarea : tareasDelUsuario) {
                Notificacion notificacion = new Notificacion(
                    preferenciaNotificacion.getDiasAntes(),
                    preferenciaNotificacion.getMinutosIntervalo(),
                    false,
                    tarea.getIdTarea(),
                    tarea.getNombreTarea(),
                    tarea.getResponsableTarea(),
                    tarea.getFechaDeVencimiento());
                
                //Inicia un nuevo hilo para cada tarea
                Thread notificacionThread = new Thread(notificacion);
                notificacionThread.start();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnNotificaciones = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProyecto = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtTarea = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGesTareas = new javax.swing.JButton();
        btnGestProyectos = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabelNombre.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setText("¡Bienvenidx !");

        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salida.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnNotificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/notificacion.png"))); // NOI18N
        btnNotificaciones.setText("Notificaciones");
        btnNotificaciones.setToolTipText("Gestión de Notificaciones");
        btnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion)
                    .addComponent(btnNotificaciones))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnNotificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion))
        );

        jtProyecto.setBackground(new java.awt.Color(204, 204, 0));
        jtProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Proyecto", "Nombre", "Responsable", "Inicio", "Fin", "¿Finalizado?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtProyecto);

        jtTarea.setBackground(new java.awt.Color(204, 204, 0));
        jtTarea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Tarea", "Proyecto", "Nombre Tarea", "Responsable Tarea", "Fecha de Vencimiento", "Prioridad", "¿Finalizada?", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtTarea);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mis Tareas");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mis Proyectos");

        btnGesTareas.setText("Gestionar Tareas");
        btnGesTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGesTareasActionPerformed(evt);
            }
        });

        btnGestProyectos.setText("Gestionar Proyectos");
        btnGestProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestProyectosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGestProyectos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGesTareas)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnGestProyectos))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnGesTareas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGesTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGesTareasActionPerformed
        this.setVisible(false);
        frmGestTarea gt = new frmGestTarea(this.usuario);
        gt.setVisible(true);
    }//GEN-LAST:event_btnGesTareasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        this.setVisible(false);
        this.dispose();
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGestProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestProyectosActionPerformed
        this.setVisible(false);
        frmGestProyecto gp = new frmGestProyecto(this.usuario);
        gp.setVisible(true);
    }//GEN-LAST:event_btnGestProyectosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesActionPerformed
        this.setVisible(false);
        frmNotificacion n = new frmNotificacion(this.usuario);
        n.setVisible(true);
    }//GEN-LAST:event_btnNotificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Usuario usuario = new Usuario();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmMenuPrincipal(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGesTareas;
    private javax.swing.JButton btnGestProyectos;
    private javax.swing.JButton btnNotificaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtProyecto;
    private javax.swing.JTable jtTarea;
    // End of variables declaration//GEN-END:variables
}
